name: build-windows

on:
  push:
    branches: [ v1.x-udt ]
  pull_request:
    branches: [ v1.x-udt ]

env:
  PYTHON_VERSION: 2.7
  FLAKY_TESTS: dontcare

jobs:
  build-windows:
    runs-on: windows-2016
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init
      - name: configure
        run: mkdir -p build && cmake -B ./build -S . -DBUILD_TESTING=ON -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DCMAKE_C_COMPILER=i686-w64-mingw32-gcc
      - name: make
        run: cmake --build build
      - name: test
        run: build/uv_run_tests

