name: build-windows

on:
  push:
    branches: [ v1.x-udt ]
  pull_request:
    branches: [ v1.x-udt ]

env:
  PYTHON_VERSION: 2.7
  FLAKY_TESTS: dontcare

jobs:
  build-windows:
    runs-on: windows-2016
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install deps
        run: choco install nasm
      - name: Environment Information
        run: npx envinfo
      - name: configure
        run: mkdir -p build && cmake -B ./build -S . -DBUILD_TESTING=ON
      - name: make
        run: cmake --build build
      - name: test
        run: build/uv_run_tests

