name: C/C++ CI

on:
  push:
    branches: [ v1.x-udt ]
  pull_request:
    branches: [ v1.x-udt ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      uses: srt32/git-actions@v0.0.3
      with:
       args: git submodule update --init --recursive  
    - name: configure
      run: mkdir -p build && cmake -B./build -H. -DBUILD_TESTING=ON
    - name: make
      run: cmake --build build
    - name: test
      run: build/uv_run_tests
