name: C/C++ CI

on:
  push:
    branches: [ v0.8-udt ]
  pull_request:
    branches: [ v0.8-udt ]

jobs:
  build:

    runs-on: ubuntu-16.04
    
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
